provider: yfinance
tickers:
  - XOM
  - CVX
  - MA
  - V
  - JPM
  - BAC
  - KO
  - PEP
start_date: "2018-10-01"
end_date: "2025-10-01"
interval: "1d"
fields: ["Adj Close", "Close", "Volume"]
force_refresh: false
